// Server-side audio cache (local disk). Content-addressed: the same
// (provider, lang, voice, rate, text) always hashes to the same key, so a clip
// is generated by the vendor at most once — across every device and reinstall,
// not just per-browser like the client IndexedDB cache. Realises principle 六's
// "音频生成一次即缓存成文件". Same key shape ports cleanly to R2 later.
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { TtsResult } from "./adapters/types";

// Relative to the server's cwd, matching db.ts's `file:./data/echo.db`.
// `server/data/` is already git-ignored.
const AUDIO_DIR = "./data/audio";

// Bytes and mime are stored as two sibling files: `<hash>.audio` + `<hash>.mime`.
// The sidecar keeps the mime exact (edge → mp3, gemini → wav, …) without
// guessing from an extension.
function audioPath(key: string): string {
  return join(AUDIO_DIR, `${key}.audio`);
}
function mimePath(key: string): string {
  return join(AUDIO_DIR, `${key}.mime`);
}

export function ttsCacheKey(parts: {
  provider: string;
  lang: string;
  voice: string;
  rate: number;
  text: string;
}): string {
  const short = parts.lang.split("-")[0]!.toLowerCase();
  const raw = `${parts.provider}|${short}|${parts.voice}|${parts.rate}|${parts.text}`;
  return createHash("sha256").update(raw).digest("hex");
}

export async function getCachedTts(key: string): Promise<TtsResult | null> {
  try {
    const audio = await readFile(audioPath(key));
    let mime = "audio/mpeg";
    try {
      const m = (await readFile(mimePath(key), "utf8")).trim();
      if (m) mime = m;
    } catch {
      // no sidecar → fall back to the default mime
    }
    return { audio, mime };
  } catch {
    return null; // cache miss (file absent)
  }
}

export async function putCachedTts(key: string, result: TtsResult): Promise<void> {
  await mkdir(AUDIO_DIR, { recursive: true });
  await writeFile(audioPath(key), result.audio);
  await writeFile(mimePath(key), result.mime, "utf8");
}
